# Copied from https://github.com/tinygrad/tinygrad/blob/master/mkdocs.yml

site_name: DeepLocalizer
site_url: https://xnought.github.io/deeplocalizer/
repo_url: https://github.com/xnought/deeplocalizer/
theme:
    name: material
    features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.path
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate
    palette:
      scheme: slate
      primary: black
      accent: orange
    palette:
      - media: "(prefers-color-scheme)"
        accent: orange
        primary: black
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        accent: orange
        primary: black
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        accent: orange
        primary: black
        toggle:
          icon: material/brightness-4
          name: Switch to system preference
markdown_extensions:
- attr_list
- admonition
- footnotes
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.inlinehilite:
    style_plain_text: python
- pymdownx.magiclink
- pymdownx.snippets:
    base_path: [!relative $config_dir]
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
# - toc:
#     permalink: "¤"

plugins:
    - search 
    - mkdocstrings:
        handlers:
          python:
            inventories:
            - https://docs.python.org/3/objects.inv
            load_external_modules: true
            paths: ["deeplocalizer"]
            options:
              docstring_options:
                ignore_init_summary: true
              docstring_section_style: table
              filters: ["!^_"]
              heading_level: 3
              inherited_members: false
              merge_init_into_class: true
              separate_signature: true
              show_root_heading: true
              show_root_full_path: false
              show_signature_annotations: true
              show_symbol_type_heading: true
              show_symbol_type_toc: true
              show_source: true
              signature_crossrefs: true
              summary: true
              annotations_path: "source"
          